-- Migration v2 : Nouvelles colonnes profil
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS telephone TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS date_naissance DATE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS ville TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS code_postal TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS pays TEXT DEFAULT 'France';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS siret TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS secteur TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS profil_complet BOOLEAN DEFAULT FALSE;
